export const CHANGE_TOP_BANNERS = 'recommend/CHANGE_TOP_BANNERS';
export const CHANGE_HOT_RECOMMENDS = 'recommend/CHANGE_HOT_RECOMMENDS';
export const CHANGE_ALBUM_NEWEST = 'recommend/CHANGE_ALBUM_NEWEST';